// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyrgXLSkeeF6Qhlsy5wdLf3HPdBlO7ShM',
    appId: '1:1019734157470:web:a85bfcc198c705d841738f',
    messagingSenderId: '1019734157470',
    projectId: 'mynotes-apptestguy',
    authDomain: 'mynotes-apptestguy.firebaseapp.com',
    storageBucket: 'mynotes-apptestguy.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbjVbV2YGwTc40cmksYixRXynXUYRopUk',
    appId: '1:1019734157470:android:7916bbdbc42b9c8041738f',
    messagingSenderId: '1019734157470',
    projectId: 'mynotes-apptestguy',
    storageBucket: 'mynotes-apptestguy.appspot.com',
  );
 
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIURyrXfdqTlq-yYW7j5vt3ARlifoK5Hg',
    appId: '1:1019734157470:ios:bea1ea212f1f1e9d41738f',
    messagingSenderId: '1019734157470',
    projectId: 'mynotes-apptestguy',
    storageBucket: 'mynotes-apptestguy.appspot.com',
    iosClientId: '1019734157470-ip228h2akr9qsh581pa5ubcrgamdlgvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tommy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIURyrXfdqTlq-yYW7j5vt3ARlifoK5Hg',
    appId: '1:1019734157470:ios:bea1ea212f1f1e9d41738f',
    messagingSenderId: '1019734157470',
    projectId: 'mynotes-apptestguy',
    storageBucket: 'mynotes-apptestguy.appspot.com',
    iosClientId: '1019734157470-ip228h2akr9qsh581pa5ubcrgamdlgvj.apps.googleusercontent.com',
    iosBundleId: 'com.example.tommy',
  );
}
